#%RAML 1.0 NamedExample

value:
-
  firstName: "Alex"
  lastName: "George"
  address: "15 Jackson Road, QLD"
  postal: "4109"
  country: "AUS"
  miles: 123
  type: "personal"
-
  firstName: "Sachin"
  lastName: "Sajan"
  address: "20 Wollongong Street, NSW"
  postal: "50000"
  country: "AUS"
  miles: 200
  type: "business"  