#%RAML 1.0 NamedExample

value:
-
  id: "1111"
  firstName: "Alex"
  lastName: "George"
  address: "15 Jackson Road, QLD"
  postal: "4109"
  country: "AUS"
  miles: 123
  creationDate: 2019-08-21T04:34:41.098Z
  type: "personal"
-
  id: "2222"
  firstName: "Sachin"
  lastName: "Sajan"
  address: "20 Wollongong Street, NSW"
  postal: "50000"
  country: "AUS"
  miles: 200
  creationDate: 2018-12-09T21:53:12.127Z
  type: "business"  